FROM "mcr.microsoft.com/devcontainers/universal:2-linux"
# Install the xz-utils package
RUN apt-get update 
# Install Vue.js
RUN npm install -g @vue/cli
# Install Flask
RUN pip install flask flask-cors
